SET NAMES UTF8;
DROP DATABASE IF EXISTS blog;
CREATE DATABASE blog CHARSET=UTF8;
USE blog;

CREATE TABLE note(
  nid INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(64),
  content VARCHAR(4096),
  pub_time VARCHAR(10)
);

CREATE TABLE collect(
  cid INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(64),
  curl VARCHAR(128),
  intr VARCHAR(256)
);

CREATE TABLE jotting(
  nid INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(64),
  content VARCHAR(4096),
  pub_time VARCHAR(10)
);

CREATE TABLE mood(
  mid INT PRIMARY KEY AUTO_INCREMENT,
  content VARCHAR(32),
  mdate VARCHAR(10)
);